name: Setup node and pnpm

description: This workflow sets up Node.js and pnpm for use in other workflows.

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 2

    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        version: 10

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
