- name: Create docker network for proxy
  docker_network:
    name: "{{ proxy_network }}"

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Create traefik directory
  file:
    path: /opt/traefik
    state: directory
    owner: deployer
    group: deployer

- name: Install passlib dependency
  apt:
    name: python3-passlib
    state: present
    update_cache: yes
  become: true

- name: Create .htpasswd file for Traefik dashboard authentication
  community.general.htpasswd:
    path: /opt/traefik/.htpasswd
    name: "{{ traefik_username }}"
    password: "{{ traefik_password }}"
    crypt_scheme: bcrypt
  become: true

- name: Create letsencrypt directory
  file:
    path: /opt/traefik/letsencrypt
    state: directory
    owner: deployer
    group: deployer
    mode: "0700"

- name: Create acme.json file
  file:
    path: /opt/traefik/letsencrypt/acme.json
    state: touch
    owner: deployer
    group: deployer
    mode: "0600"

- name: Deploy Traefik config file
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    owner: deployer
    group: deployer
    mode: "0600"

- name: Deploy Traefik compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    owner: deployer
    group: deployer
    mode: "0600"
- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
