name: Application lint checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Check all linting
        run: pnpm nx affected --target=lint --base=origin/main --head=HEAD

      - name: Get affected production apps
        id: set-matrix
        run: |
          affected=$(pnpm nx show projects --affected --type=app --json --base=origin/main --head=HEAD)
          echo "Affected apps: $affected"
          echo "apps=$affected" >> $GITHUB_OUTPUT


  check:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.lint.outputs.apps) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Matrix lint
        run: pnpm nx build ${{ matrix.app }}
