name: Pr create

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  lint-check:
    uses: ./.github/workflows/lint-check.yml
    with:
      base_branch: origin/main

  get_effected_apps:
    needs: lint-check
    uses: ./.github/workflows/frontend-effected-apps-list.yml
    with:
      base_branch: origin/main

  build_effected_apps:
    needs: get_effected_apps
    uses: ./.github/workflows/frontend-effected-apps-build-release.yml
    with:
        base_branch: origin/main
        effectedApps: ${{ needs.get_effected_apps.outputs.effected_apps || '[]' }}
        isPr: true
        password: ${{ secrets.DOCKER_PASSWORD }}
