name: Close the PR and cleanup PR environment

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  get_short_sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.extract.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract short SHA
        id: extract
        run: |
          SHORT_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
  close-pr:
    uses: ./.github/workflows/pr-cleanup.yml
    secrets: inherit
    with:
      delete_hash: ${{ steps.get_short_sha.outputs.short_sha }}

