name: apps build

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      tag:
        required: true
        type: string

    outputs:
      effected_apps:
        description: List of effected apps
        value: ${{ jobs.run_build.outputs.effected_apps }}

jobs:
  run_build:
    runs-on: ubuntu-latest

    outputs:
      effected_apps: ${{ steps.get-nextjs-apps.outputs.effected_apps }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Get affected production apps
        id: get-nextjs-apps
        run: |
          affected=$(pnpm nx show projects --affected --projects=tag:${{ inputs.tag }} --json --base=${{ inputs.base_branch }} --head=HEAD)

          if [ -z "$affected" ]; then
            affected="[]"
          fi

          echo "effected_apps=$affected" >> $GITHUB_OUTPUT
