name: frontend apps build and release

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      effectedApps:
        required: true
        type: string
      isPr:
        required: true
        type: boolean
      app_framework:
        required: true
        type: string
      releaseEnv:
        required: false
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true
      SSH_KEY:
        required: true

jobs:
  run_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(inputs.effectedApps) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: registry.falcon-head.org
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build affected Next.js app
        run: |
          pnpm nx build ${{ matrix.app }} --skip-nx-cache
          if ["${{ inputs.app_framework }}" = "NestApp"]; then
            pnpm nx prune ${{ matrix.app }} --skip-nx-cache
          fi

      - name: Extract app name
        id: extract
        run: |
          RAW="${{ matrix.app }}"
          APP_NAME="${RAW##*/}"
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build_and_publish
        run: |
          docker build -t registry.falcon-head.org/${{ steps.extract.outputs.app_name }}:${{ inputs.isPr && github.event.pull_request.number || inputs.releaseEnv }} -f ./infra/Dockerfiles/${{inputs.app_framework}}.Dockerfile --build-arg APP_NAME=${{ steps.extract.outputs.app_name }} .
          docker push registry.falcon-head.org/${{ steps.extract.outputs.app_name }}:${{ inputs.isPr && github.event.pull_request.number || inputs.releaseEnv }}
          echo "app_name=$"

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          port: ${{ vars.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # stop on error (VERY IMPORTANT)

            cd /opt/apps/${{ inputs.isPr && 'pr-env' || inputs.releaseEnv }}

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.falcon-head.org \
            -u ${{ vars.DOCKER_USERNAME }} --password-stdin

            export APP_NAME=${{ steps.extract.outputs.app_name }}
            export PR_NUMBER="prod"

            if [ "${{ inputs.isPr }}" = "true" ]; then

              TARGET_DIR="./pr-${{ steps.extract.outputs.app_name }}/${{ github.event.pull_request.number }}"

              if [ -d "$TARGET_DIR" ]; then
                echo "Folder already exists, skipping..."
              else
                mkdir -p "$TARGET_DIR"
                echo "Folder created"
              fi

              export PR_NUMBER=${{ github.event.pull_request.number }}

              cd "$TARGET_DIR"

              envsubst < "/opt/apps/pr-template/docker-compose.yml" > docker-compose.yml
            fi

            docker compose pull
            docker compose up -d --remove-orphans
