name: lint check

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Check all linting
        run: pnpm nx affected --target=lint --base=${{ inputs.base_branch }} --head=HEAD
