name: PR Checks

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run lint check
        run: pnpm nx affected --target=lint --parallel --max-parallel=5 --base=origin/main --head=HEAD

  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run ts check
        run: pnpm nx affected --target=ts-check --parallel --max-parallel=5 --base=origin/main --head=HEAD

  clean-old-pr:
    runs-on: ubuntu-latest
    needs: [lint-check, ts-check]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup node and pnpm
        uses: ./github/actions/clean-old-pr


  get-affected-apps:
    runs-on: ubuntu-latest
    needs: clean-old-pr
    outputs:
      affected_apps: ${{ steps.affected-apps.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Get affected apps
        id: affected-apps
        run: |
          echo "affected_apps=$(pnpm nx show projects --affected --projects=tag:type:app --json --base=origin/main --head=HEAD)"

          echo "affected_apps=$affected_apps" >> $GITHUB_OUTPUT

  build-and-push-affected-apps:
    runs-on: ubuntu-latest
    needs: get-affected-apps
    if: needs.get-affected-apps.outputs.affected_apps != '[]'
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.affected_apps) }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - uses: ./.github/actions/build-and-push-app
