name: pr-cleanup

on:
  workflow_call:
    secrets:
      DOCKER_PASSWORD:
        required: true
      SSH_KEY:
        required: true

jobs:
  clean-pr-environments:
    name: Clean pr environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: ssh to server and cleanup
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          port: ${{ vars.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            BASE_DIR="/opt/apps/pr-env"

            SHORT_SHA=${{ github.event.pull_request.head.sha | cut -c1-7 }}
            PREVIOUS_SHORT_SHA="${{ git rev-parse HEAD^ | cut -c1-7 }}"

            TARGET_DIR="$BASE_DIR/pr-${{github.event.pull_request.number }}-${{ inputs.delete_hash }}"

            if [ -d "$TARGET_DIR" ]; then
              echo "Folder exists, deleting..."
              find $TARGET_DIR -mindepth 1 -maxdepth 1 -type d | while IFS= read -r folder; do
                echo "Processing $folder"

                if [ -f "$folder/docker-compose.yml" ]; then
                  echo "Stopping docker compose in $folder"
                  (cd "$folder" && docker compose down)
                fi

                echo "Deleting $folder"
                rm -rf "$folder"

                echo "Done with $folder"
                echo "---------------------"
              done
            else
              echo "Folder does not exist, skipping..."
              exit 0
