name: PR Checks

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node and pnpm
        uses: ./.github/workflows/actions/setup-node-pnpm

      - name: Run lint check
        run: pnpm nx affected --target=lint --parallel --max-parallel=5 --ci --base=origin/main --head=HEAD

  ts-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node and pnpm
        uses: ./.github/workflows/actions/setup-node-pnpm

      - name: Run ts check
        run: pnpm nx affected --target=ts-check --parallel --max-parallel=5 --ci --base=origin/main --head=HEAD
